SELECT * FROM bill WHERE BILL_ID=1 ==>ZEIGT DIE INFOS DES CUSTOMERS DER DEN BILL ID 1 HAT.

SELECT * FROM bill WHERE BILL_ID>2 ==>ZEIGT DIE INFOS DER CUSTOMERS DER DEN BILL_ID ÜBER 2 HAT.

SELECT * FROM customer WHERE ID=1 or ID=3 ==>ZEIGT DIE INFOS DER CUSTOMER DER DEN ID 1 oder 3 HAT.

SELECT * FROM bill ORDER BY PRICE ASC ==>ZEIGT DEN PRICE ZUM TIEFSETEN->HÖCHSTEN PRICE
SELECT * FROM bill ORDER BY PRICE DESC ==>ZEIGT DEN PRICE ZUM HÖCHSTEN->TIEFSTEN PRICE

UPDATE customer SET NAME='JOHN' WHERE ID=1 ==> UPDATED DEN CUSTOMER DER DEN ID 1 HAT
DELETE customer where ID=1 ==> LÖSCHT DEN CUSTOMER DER DEN ID 1 HAT.

SELECT SUM(PRICE) FROM bill ==> ADDIERT DIE GANZEN PRICE BEI BILL TABLE DIE VERFÜGBAR SIND. 

SELECT ID,NAME FROM customer INNER JOIN bill ON bill.BILL_ID=customer.ID
SELECT NAME FROM customer LEFT JOIN reservation ON reservation.RESERVATION_ID=customer.ID
